version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: unleash
      POSTGRES_USER: unleash
      POSTGRES_PASSWORD: unleash
    volumes:
      - unleash-data:/var/lib/postgresql/data
    networks:
      - micro-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unleash"]
      interval: 10s
      timeout: 5s
      retries: 5

  unleash-server:
    image: unleashorg/unleash-server:latest
    container_name: unleash-server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://unleash:unleash@postgres:5432/unleash
      DATABASE_SSL: "false"
      AUTH_TYPE: none
    ports:
      - "4242:4242"
    networks:
      - micro-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4242/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    build: ./productService
    container_name: product-service
    ports:
      - "8081:8081"
    networks:
      - micro-net
    environment:
      SPRING_PROFILES_ACTIVE: docker
      UNLEASH_API_URL: http://unleash-server:4242/api
      UNLEASH_API_TOKEN: default-client-token
      UNLEASH_APP_NAME: product-service
    depends_on:
      unleash-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/products"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build: ./orderService
    container_name: order-service
    ports:
      - "8082:8082"
    networks:
      - micro-net
    environment:
      SPRING_PROFILES_ACTIVE: docker
      UNLEASH_API_URL: http://unleash-server:4242/api
      UNLEASH_API_TOKEN: default-client-token
      UNLEASH_APP_NAME: order-service
    depends_on:
      product-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/orders"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  micro-net:

volumes:
  unleash-data: