version: "3.9"

services:

  product-service:
    build: ./productService
    ports:
      - "8081:8081"
    networks:
      - micro-net
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/products"]
      interval: 10s
      retries: 5

  order-service:
    build: ./orderService
    ports:
      - "8082:8082"
    networks:
      - micro-net
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      product-service:
        condition: service_healthy

networks:
  micro-net:
