server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:orders
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

product:
  service:
    url: http://localhost:8081
unleash:
  api-url: http://localhost:4242/api
  app-name: order-service
  instance-id: order-service-1